config/routes.rb
Rails.application.routes.draw do


  get 'ingredients/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [ :new, :create ]
  end

resources :doses, only: :destroy
resources :ingredients, only: :show
root "cocktails#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
  # before_destroy :check_for_doses


  private

  # def check_for_doses
  #   if doses.count > 0
  #     errors.add_to_base("cannot delete ingredient when used by a cocktail")
  #     return false
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktails = Cocktail.all
    @dose = Dose.new
  end


  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      redirect_to cocktails_path
    end
  end


  private
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :photo_cache)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only:[:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:dose_id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class= "container">

  <div class = "row">
    <div class ="col-xs-12 col-md-8" >
      <h1 class ="text-center">Enjoy our baby bottle cocktails !</h1>
    </div>

    <div class = "col-xs-12 col-md-4" >
      <h1 class ="text-center">... or make your own!</h1>
    </div>

  </div>

  <div class = "row">

    <div class ="col-xs-12 col-md-8">

      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to cocktail_path(cocktail) do %>

            <% if cocktail.photo.url %>

              <div class="card image-spin" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path cocktail.photo, height: 200, width: 400, crop: :fill %>')">
                <div class="card-description">
                  <h2><%= cocktail.name %></h2>
                  <%  cocktail.ingredients.each do |ingredient| %>
                    <%= ingredient.name %>
                  <% end %>
                </div>
              </div>

            <% else %>

              <div class="card image-spin" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= image_path("babybottle.png") %>);">
                <div class="card-description">
                  <h2><%= cocktail.name %></h2>
                  <%  cocktail.ingredients.each do |ingredient| %>
                    <%= ingredient.name %>
                  <% end %>
                </div>
              </div>

            <% end %>

          <% end %>
        </div>
      <% end %>
    </div>

    <div class = "col-xs-12 col-md-4">

      <%= simple_form_for(@cocktail) do |f| %>

        <%= f.input :name, placeholder: "Mojito" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Add a cocktail", class:"navbar-wagon-item navbar-wagon-button btn btn-size" %>
      <% end %>

      <%= image_tag "baby drinker.jpg", class: "community" %>

      <%= link_to "Join the community", "#", class:"navbar-wagon-item navbar-wagon-button btn btn-size" %>

    </div >

  </div>

</div>

app/views/cocktails/show.html.erb
<div class="container ">

  <h2 class ="text-center">Enjoy your <%= @cocktail.name %></h2>

  <div class = "row">

    <% if @cocktail.photo.url %>

      <div class ="col-xs-12 col-md-6">
        <%= cl_image_tag @cocktail.photo, height: 400, width: 500, crop: :fill %>
      </div>

    <% else %>

      <div class ="col-xs-12 col-md-6">
        <%= image_tag "cocktailback.jpg", height: 400, width: 500, class: "img-responsive"%>
      </div>

    <% end %>



    <div class ="col-xs-12 col-md-6">
      <p><%= @cocktail.name %> is made by your favourite barman with the following <strong> ingredients </strong> : </p>
      <dl class="dl-horizontal text-overflow">
        <% @cocktail.doses.each do|dose| %>
          <dt class = "text-overflow">
            <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %>
          </dt>
          <dd>
            <%= dose.description.capitalize %>
            <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash"></i>
            <% end %>
          </dd>
        <% end %>
      </dl>
    </div>
  </div>

  <div class = "row">

    <div class ="col-md-offset-6 col-xs-12 col-md-6">
      <h4>Add an ingredient to <%= @cocktail.name %></h4>

        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient %>
          <%= f.input :description %>
          <%= f.submit "add an ingredient", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>

</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<div class ="container">
  <h1>Add an ingredient to <%= @cocktail.name %></h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "add an ingredient", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/ingredients/show.html.erb
<div class = "container">

  <h1>These are all the cocktails that are made with <%= @ingredient.name %>. </h1>
  <h4> Will you try them all?</h4>

  <div class = "row">
    <% @ingredient.cocktails.each do |cocktail| %>

      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://lorempixel.com/400/200/food');">
            <div class="card-category"><%= cocktail.name %></div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Pangolin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch" rel="stylesheet">

  </head>

  <body class = "body">
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <%= image_tag "bib.png", class: "bib_image image-spin" %>

  <h1> Welcome to Club Biberon </h1>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>


   <!-- avatar et join the comunity -->


    <!-- Button (call-to-action) -->
    <%= link_to "Our cocktails", cocktails_path, class:"navbar-wagon-item navbar-wagon-button btn btn-size" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>